"""Add forensic fields back to Report model

Revision ID: 9b059a3ed9cd
Revises: b8b0903f8b96
Create Date: 2025-10-14 19:16:28.428824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b059a3ed9cd'
down_revision = 'b8b0903f8b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forensic_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('forensic_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('forensic_details')
        batch_op.drop_column('forensic_summary')

    # ### end Alembic commands ###
