"""Add new fields to Report model

Revision ID: b8b0903f8b96
Revises: 
Create Date: 2025-10-14 18:58:00.310449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b0903f8b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('complaint_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('incident_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delay_in_reporting', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('evidence_file', sa.String(length=200), nullable=True))
        batch_op.drop_column('date_of_incident')
        batch_op.drop_column('evidence_text')
        batch_op.drop_column('suspect_guess')
        batch_op.drop_column('incident_type')
        batch_op.drop_column('location')
        batch_op.drop_column('file_metadata')
        batch_op.drop_column('clues')
        batch_op.drop_column('forensic_details')
        batch_op.drop_column('artifacts')
        batch_op.drop_column('forensic_summary')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('forensic_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('artifacts', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('forensic_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('clues', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('file_metadata', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('incident_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('suspect_guess', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('evidence_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('date_of_incident', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('evidence_file')
        batch_op.drop_column('platform')
        batch_op.drop_column('delay_in_reporting')
        batch_op.drop_column('incident_date')
        batch_op.drop_column('complaint_category')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
